# Packages used in my analysis
# to update after an new R version download

install.packages("gglot")
install.packages("ggplot2")            
install.packages("AER")
install.packages("apt")
install.packages("calibrate")
install.packages("cluster")
install.packages("dbplyr")
install.packages("dplyr")
install.packages("devtools")
install.packages("dslabs")
install.packages("erer")
install.packages("xlsx")               
install.packages("calibrate")           
install.packages("reshape2")           
install.packages("ggpubr")
install.packages("ggmap")
install.packages("mapproj")
